"""Project-wide defaults for growingnn."""

import numpy as np

FLOAT_TYPE = np.float32

RESHEPERS_CACHE_MAX_SIZE = 10
RESHEPERS_CACHE_MAX_MEMORY_MB = 100
RESHEPERS_CACHE_ENABLE_MONITORING = True


ADDING_RES_LAYERS_WEIGHT_INITIALIZATION_RANGE = (0.0, 0.01)
RES_CONV_TO_LINEAR_GLOBAL_POOL_TYPE = "max"  # "avg" | "max"